"""add bets, ledger and admin flag

Revision ID: 32c50e3c9e37
Revises: c9cba8507d32
Create Date: 2026-10-06 21:29:25.539904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '32c50e3c9e37'
down_revision: Union[str, Sequence[str], None] = 'c9cba8507d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stake_cents', sa.BigInteger(), nullable=False),
    sa.Column('potential_payout_cents', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', 'VOID', name='bet_status'), nullable=False),
    sa.Column('payout_cents', sa.BigInteger(), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_status'), 'bets', ['status'], unique=False)
    op.create_index(op.f('ix_bets_user_id'), 'bets', ['user_id'], unique=False)
    op.create_table('bet_legs',
    sa.Column('bet_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('market', postgresql.ENUM(name='market', create_type=False), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('price_american', sa.Integer(), nullable=False),
    sa.Column('point', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=True),
    sa.Column('result', sa.Enum('PENDING', 'WON', 'LOST', 'PUSH', name='leg_result'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bet_legs_bet_id'), 'bet_legs', ['bet_id'], unique=False)
    op.create_index(op.f('ix_bet_legs_game_id'), 'bet_legs', ['game_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_cents', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('SIGNUP_BONUS', 'BET_STAKE', 'BET_PAYOUT', 'BET_REFUND', 'ADMIN_ADJUSTMENT', name='ledger_kind'), nullable=False),
    sa.Column('bet_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_bet_id'), 'ledger_entries', ['bet_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id'), 'ledger_entries', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Existing accounts got their starting balance before the ledger existed. Record it as
    # a signup bonus so every user's ledger sums to their balance.
    op.execute(
        """
        INSERT INTO ledger_entries
            (id, user_id, amount_cents, balance_after_cents, kind, created_at, updated_at)
        SELECT gen_random_uuid(), id, balance_cents, balance_cents, 'SIGNUP_BONUS',
               created_at, created_at
        FROM users
        WHERE balance_cents <> 0
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_ledger_entries_user_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_bet_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_bet_legs_game_id'), table_name='bet_legs')
    op.drop_index(op.f('ix_bet_legs_bet_id'), table_name='bet_legs')
    op.drop_table('bet_legs')
    op.drop_index(op.f('ix_bets_user_id'), table_name='bets')
    op.drop_index(op.f('ix_bets_status'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
    for enum_name in ('ledger_kind', 'leg_result', 'bet_status'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
