"""add kind to odds fetches

Revision ID: 65af980b9752
Revises: 32c50e3c9e37
Create Date: 2026-10-06 22:14:38.954470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65af980b9752'
down_revision: Union[str, Sequence[str], None] = '32c50e3c9e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds_fetches', sa.Column('kind', sa.String(length=16), server_default='odds', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds_fetches', 'kind')
    # ### end Alembic commands ###
