"""add games and odds

Revision ID: c9cba8507d32
Revises: 24f61b2174c7
Create Date: 2026-10-06 14:27:52.989149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cba8507d32'
down_revision: Union[str, Sequence[str], None] = '24f61b2174c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('sport_key', sa.String(length=64), nullable=False),
    sa.Column('home_team', sa.String(length=100), nullable=False),
    sa.Column('away_team', sa.String(length=100), nullable=False),
    sa.Column('commence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_games_commence_time'), 'games', ['commence_time'], unique=False)
    op.create_index(op.f('ix_games_sport_key'), 'games', ['sport_key'], unique=False)
    op.create_table('odds_fetches',
    sa.Column('sport_key', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('requests_remaining', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_fetches_sport_key'), 'odds_fetches', ['sport_key'], unique=False)
    op.create_table('odds_lines',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.Enum('H2H', 'SPREADS', 'TOTALS', name='market'), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('price_american', sa.Integer(), nullable=False),
    sa.Column('point', sa.Numeric(precision=5, scale=1, asdecimal=False), nullable=True),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'market', 'outcome', name='uq_odds_line_game_market_outcome')
    )
    op.create_index(op.f('ix_odds_lines_game_id'), 'odds_lines', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_lines_game_id'), table_name='odds_lines')
    op.drop_table('odds_lines')
    op.drop_index(op.f('ix_odds_fetches_sport_key'), table_name='odds_fetches')
    op.drop_table('odds_fetches')
    op.drop_index(op.f('ix_games_sport_key'), table_name='games')
    op.drop_index(op.f('ix_games_commence_time'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
    sa.Enum(name='market').drop(op.get_bind(), checkfirst=True)
